-- up
CREATE TABLE IF NOT EXISTS hosts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  host_name VARCHAR(255) NOT NULL UNIQUE,
  -- Reachability & scan tracking fields (merged from later migration FR017/FR019)
  is_reachable TINYINT(1) NOT NULL DEFAULT 0,
  last_checked_utc DATETIME(6) NULL,
  last_reachable_utc DATETIME(6) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS certificates (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  host_id BIGINT UNSIGNED NOT NULL,
  serial_number VARCHAR(128) NOT NULL,
  expiration_utc DATETIME(6) NOT NULL,
  retrieved_at_utc DATETIME(6) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_certificates_host_id (host_id),
  CONSTRAINT fk_cert_host FOREIGN KEY (host_id) REFERENCES hosts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- down
DROP TABLE IF EXISTS certificates;
DROP TABLE IF EXISTS hosts;
